In [2]:
import datetime
import pandas as pd
import numpy as np
import sys
import os
sys.path.append(r'/Users/jerrytang/Desktop/current/Capstone/')
import yfinance as yf

from nasdaq_100_ticker_history.load import get_nasdaq100_tickers

In [4]:
nasdaq = yf.Ticker("HSTECH.HK")
intraday_data = nasdaq.history(period="8d", interval="1m")
intraday_data.to_csv('HSTECH.csv')

In [6]:
nasdaq = yf.Ticker("HKDCNH=X")
intraday_data = nasdaq.history(period="8d", interval="1m")
intraday_data.to_csv('HKDCNH.csv')

In [10]:
intraday_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2025-04-04 00:00:00+01:00,1.0676,1.0676,1.0676,1.0676,0,0.0,0.0
2025-04-04 00:01:00+01:00,1.0677,1.0677,1.0677,1.0677,0,0.0,0.0
2025-04-04 00:02:00+01:00,1.0677,1.0677,1.0677,1.0677,0,0.0,0.0
2025-04-04 00:03:00+01:00,1.0677,1.0677,1.0677,1.0677,0,0.0,0.0
2025-04-04 00:04:00+01:00,1.0677,1.0677,1.0677,1.0677,0,0.0,0.0
...,...,...,...,...,...,...,...
2025-04-15 08:56:00+01:00,1.0602,1.0602,1.0602,1.0602,0,0.0,0.0
2025-04-15 08:57:00+01:00,1.0604,1.0604,1.0604,1.0604,0,0.0,0.0
2025-04-15 08:58:00+01:00,1.0604,1.0604,1.0604,1.0604,0,0.0,0.0
2025-04-15 08:59:00+01:00,1.0603,1.0603,1.0603,1.0603,0,0.0,0.0
2025-04-15 09:00:00+01:00,1.0604,1.0604,1.0604,1.0604,0,0.0,0.0

In [31]:
# get all components 2024
tickers = []
for date in pd.date_range(start='2024-01-01', end='2024-12-31'):
    t = get_nasdaq100_tickers(date.strftime('%Y-%m-%d'))
    tickers += t

tickers = sorted(set(tickers))
tickers

['AAPL',
 'ABNB',
 'ADBE',
 'ADI',
 'ADP',
 'ADSK',
 'AEP',
 'AMAT',
 'AMD',
 'AMGN',
 'AMZN',
 'ANSS',
 'APP',
 'ARM',
 'ASML',
 'AVGO',
 'AXON',
 'AZN',
 'BIIB',
 'BKNG',
 'BKR',
 'CCEP',
 'CDNS',
 'CDW',
 'CEG',
 'CHTR',
 'CMCSA',
 'COST',
 'CPRT',
 'CRWD',
 'CSCO',
 'CSGP',
 'CSX',
 'CTAS',
 'CTSH',
 'DASH',
 'DDOG',
 'DLTR',
 'DXCM',
 'EA',
 'EXC',
 'FANG',
 'FAST',
 'FTNT',
 'GEHC',
 'GFS',
 'GILD',
 'GOOG',
 'GOOGL',
 'HON',
 'IDXX',
 'ILMN',
 'INTC',
 'INTU',
 'ISRG',
 'KDP',
 'KHC',
 'KLAC',
 'LIN',
 'LRCX',
 'LULU',
 'MAR',
 'MCHP',
 'MDB',
 'MDLZ',
 'MELI',
 'META',
 'MNST',
 'MRNA',
 'MRVL',
 'MSFT',
 'MSTR',
 'MU',
 'NFLX',
 'NVDA',
 'NXPI',
 'ODFL',
 'ON',
 'ORLY',
 'PANW',
 'PAYX',
 'PCAR',
 'PDD',
 'PEP',
 'PLTR',
 'PYPL',
 'QCOM',
 'REGN',
 'ROP',
 'ROST',
 'SBUX',
 'SIRI',
 'SMCI',
 'SNPS',
 'SPLK',
 'TEAM',
 'TMUS',
 'TSLA',
 'TTD',
 'TTWO',
 'TXN',
 'VRSK',
 'VRTX',
 'WBA',
 'WBD',
 'WDAY',
 'XEL',
 'ZS']

In [ ]:
cur_dt = datetime.datetime.now().date()
recent = pd.bdate_range(start='2024-01-01', end=cur_dt, freq='B')

pre_dt = max(filter(lambda dd: dd.date() < cur_dt, recent))

test = blp.bdib(tickers[:5], dt=pre_dt, session='day')
test

datetime.date(2025, 4, 11)

In [ ]:
test_all = []
for date in pd.date_range(start='2024-01-01', end=pre_dt, freq='B'):
    test_all.append(
        blp.bdib(tickers, dt=date, session='day')
    )
test_all = pd.concat(test_all)

NameError: name 'blp' is not defined